repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.2.10
  hooks:
  - id: nbdev_clean
  #- id: nbdev_export
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0  # Use the ref you want to point at
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=45000']
  - id: check-merge-conflict